sudo: required
services:
  - docker
before_install:
  - docker build -t weezyval/containerization-docker-aws -f Dockerfile.dev .
script:
  - docker run weezyval/Containerization-docker-aws npm run test